# Buck-lab router overrides.

ctrl:
  endpoint: ziti-controller-ctrl.ziti.svc:443

edge:
  advertisedHost: ziti-router.buck-lab-k8s.omlabs.org

linkListeners:
  transport:
    advertisedHost: ziti-router-transport.buck-lab-k8s.omlabs.org

persistence:
  storageClass: longhorn-r2

image:
  repository: harbor.buck-lab-k8s.omlabs.org/openziti/ziti-router

nodeSelector:
  om-labs.io/storage-node: "true"
