# Buck-lab controller overrides.

clientApi:
  advertisedHost: ziti-ctrl-buck.omlabs.org

ctrlPlane:
  advertisedHost: ziti-ctrl-buck.omlabs.org

persistence:
  storageClass: longhorn-r2

image:
  repository: harbor.buck-lab-k8s.omlabs.org:32632/openziti/ziti-controller
  tag: "1.7.2"

# Keep controller on storage nodes (persistent BoltDB).
nodeSelector:
  om-labs.io/storage-node: "true"
