apiVersion: v1
kind: Namespace
metadata:
  name: ziti
  labels:
    # OpenZiti does not require privileged PodSecurity. Keep this explicit.
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    # Encourage tightening over time without breaking installs.
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
